[package]
name = "safemem_c-to-rust_memory_safety_demo"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "c_buffer_tester"
path = "src/main.rs"

[dependencies]
libc = "0.2"

[build-dependencies]
cc = "1.0"