[package]
name = "safemem_c-to-rust_memory_safety_demo"
version = "0.1.0"
edition = "2024"

[lib]
name = "safemem"
path = "src/lib.rs"

[dependencies]

[build-dependencies]
bindgen = "0.71.1"
cc = "1.0"
